import Banner from "./Banner";
import FunFacts from "./FunFacts";
import History from "./History";
import ServicesSection from "./ServicesSection";
import WorkingFor from "./WorkingFor";
import Footer from "./Footer";
import Header from "./Header";
import Faq from "./Faq";
import Solution from "./Solution";
import Sources from "./Sources";
import Packages from "./Packages";
import BannerPage from "./BannerPage";
export { Banner, FunFacts, History, ServicesSection, WorkingFor, Footer, Header, Faq, Solution, Sources, Packages, BannerPage };